# Generated by Django 6.0.2 on 2026-04-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrokerApp', '0002_otpcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('address_name', models.TextField(blank=True, null=True)),
                ('receiver_name', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True, verbose_name='sent dte')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('address_name', models.TextField(blank=True, null=True)),
                ('receiver_name', models.TextField(blank=True, null=True)),
                ('amount', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True, verbose_name='sent dte')),
                ('time', models.TimeField(auto_now=True, verbose_name='sent time')),
            ],
        ),
    ]
