# Generated by Django 6.0.2 on 2026-04-04 06:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrokerApp', '0004_useraccount_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='info',
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['sender'], name='BrokerApp_h_sender__0e575c_idx'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['receiver'], name='BrokerApp_h_receive_7618fa_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['investor', 'due'], name='BrokerApp_i_investo_a609a2_idx'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['receiver'], name='BrokerApp_o_receive_a3f57c_idx'),
        ),
    ]
