# Generated by Django 6.0.2 on 2026-04-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrokerApp', '0006_alter_useraccount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
