# Generated by Django 6.0.2 on 2026-04-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrokerApp', '0007_alter_useraccount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
