# Generated by Django 6.0.2 on 2026-04-16 04:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BrokerApp', '0008_history_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History',
            new_name='Trasaction',
        ),
        migrations.RenameIndex(
            model_name='trasaction',
            new_name='BrokerApp_t_sender__ce921f_idx',
            old_name='BrokerApp_h_sender__0e575c_idx',
        ),
        migrations.RenameIndex(
            model_name='trasaction',
            new_name='BrokerApp_t_receive_fedce3_idx',
            old_name='BrokerApp_h_receive_7618fa_idx',
        ),
    ]
