# Generated by Django 6.0.2 on 2026-04-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrokerApp', '0009_rename_history_trasaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trasaction',
            name='created_at',
            field=models.TimeField(auto_now=True, null=True, verbose_name='transaction time'),
        ),
        migrations.AlterField(
            model_name='trasaction',
            name='created_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='transaction date'),
        ),
    ]
